### ISSUE TITLE
Support for HTTP errors payload

### ISSUE THREAD

**Issue by mantzas** [mantzas/patron#264]
## Is your feature request related to a problem? Please describe

When patron's sync handler func returns a error we do not support returning a payload.
We would like to idealy return a payload which could be following "standards" like jsonapi.org.

## Describe the solution

package sync contains a file errors.go which contains available ready for use errors which map to specific http status code.
we should add a payload of type interface{} and, if not nil, encode it to the response.

The errors.go are http specific and should be moved to the http package.

**Comment by c0nstantx** [comment]
@mantzas How willing are we to use our own `patronError` struct and not plain `go` `error`?
If we are going to add error payload we could add error code too (or even custom headers) and have full access to error responses.
We could keep (and upgrade to `patronError`) existing errors for convenience and just add the extra logic in the `handleError` function.

**Comment by mantzas** [comment]
@c0nstantx since the error will live in the HTTP package it can get more HTTP specific things like status code and payload and it should. I would not go so far to add headers yet until the need arises.
the sync package, which defines the abstraction uses the plain error interface.

**Comment by c0nstantx** [comment]
That's the issue. If we want to use a "superset" of `error` in `http` package and use it in our app's handlers we will break current compatibility. Hence the question if we are willing to do that.
For example, `handleError` method in `sync/http/handler.go` will have to accept the new error interface. Also `sync.ProcessorFunc` will have to change return signature according to new error.

Is there another alternative that won't break compatibility ?

**Comment by mantzas** [comment]
this is not the case since the the handleError lives in the http package and does not get exported so nothing breaks.
sync.ProcessorFunc wil no change at all... it will still return error and not something specific to http.
Let's wait for the implementation to confirm your concerns.
