### ISSUE TITLE
Update docker compose for support with Apple M1 sillicon

### ISSUE THREAD

**Issue by wishperera** [mantzas/patron#287]
## Is your feature request related to a problem? Please describe

Out of the box docker compose fails with error `no-matching-manifest-for-linux-arm64-v8 in the manifest list entries` for mysql image,  in apple sillicon M1 hosts

## Describe the solution

As described in the known issues section in the official documentation [here](https://docs.docker.com/desktop/mac/apple-silicon/) , add `paltform: linux/amd64` to the `db` section.

## Additional context**

<img width="841" alt="Screenshot 2022-03-30 at 11 20 30" src="https://user-images.githubusercontent.com/19636806/160797864-f7a1cbb3-4325-4f06-a773-64bd3ba8accf.png">
.

**Comment by mantzas** [comment]
@wishperera hey, thanks for mentioning it. Since the project is forked and actively maintained in this [repo](https://github.com/beatlabs/patron) would you like to try it out there to see if the problem still exists? The repos have diverged significantly.
